import { IsString, Matches, MaxLength, MinLength } from 'class-validator';
import { TrimMessageBody } from '../../messaging/dto/trim-message-body';
import { OFFICIAL_MESSAGE_MAX_LENGTH } from '../official-messages.constants';

/**
 * `POST /admin/official-messages/members/:memberId`. The body is sanitised by
 * the same transform a member's own message uses (`TrimMessageBody`) BEFORE
 * the length bounds run, so whitespace or control bytes never count toward
 * the minimum. `MessagingCoreService.postMessage` applies it again at write.
 */
export class SendOfficialMessageDto {
  @TrimMessageBody()
  @IsString()
  @MinLength(1)
  @MaxLength(OFFICIAL_MESSAGE_MAX_LENGTH)
  body!: string;
}

/**
 * `POST /admin/official-messages/broadcast`. `idempotencyKey` is generated by
 * the client once per composed broadcast (`crypto.randomUUID()`), so a
 * double-click or a retried request is the same broadcast.
 */
export class CreateOfficialBroadcastDto extends SendOfficialMessageDto {
  @IsString()
  @Matches(/^[A-Za-z0-9_-]{8,128}$/)
  idempotencyKey!: string;
}
